---
title: Serving a machine learning model via API
author: Stefan
date: 2018-04-04
categories:
  - R
tags:
  - machine_learning
  - API
  - plumer
---



<div id="about-the-plumer-package" class="section level2">
<h2>About the Plumer package</h2>
<p>In oder to serve our API we will make use of the great Plumer package in R</p>
<div class="figure">
<img src="/Pictures/Plumer.png" />

</div>
<p>To read more about this package go to:<br />
<a href="https://www.rplumber.io/docs/" class="uri">https://www.rplumber.io/docs/</a></p>
</div>
<div id="setup" class="section level2">
<h2>Setup</h2>
<p>Load in some packages.<br />
If you are going to host the api on a suse or redhat linux server make sure you have all the dependencies as well as the packages installed to follow through this example yourself.</p>
<pre class="r"><code>library(EightyR)
load_toolbox()
load_pkg(c(&quot;plumber&quot;,&quot;caret&quot;))</code></pre>
<p>In order to serve an api you need to store all the functions that you want to serve inside a R script.</p>
</div>
<div id="hello-world-example" class="section level2">
<h2>Hello world example</h2>
<p>As our “hello world” example we create a script called <code>hello_api.R</code>:</p>
<pre class="r"><code>#hello_api.R

#* @get /mean
normalMean &lt;- function(samples=10){
  data &lt;- rnorm(samples)
  mean(data)
}

#* @post /sum
addTwo &lt;- function(a, b){
  as.numeric(a) + as.numeric(b)
}</code></pre>
<p>Notice that we use the special comments #* to denote the type of api request and also the name of the request.</p>
<p>We can spin up this api on a specified local port using the following R code in another script <code>run_hello_api.r</code>:</p>
<pre class="r"><code>#!/usr/bin/Rscript

# run_hello_api.r
library(EightyR)
load_toolbox()
load_pkg(&quot;plumber&quot;)

r &lt;- plumb(&quot;hello_api.R&quot;)  # Where &#39;plumber.R&#39; is the location of the file shown above
r$run(host = &quot;0.0.0.0&quot;, port=8000)</code></pre>
<p>Remember to give this file execution rights if you want to run it using ./, you can do this using the command <code>chmod</code></p>
<p>We will run this process in a shell using the following bash code:</p>
<pre class="r"><code>./run_hello_api.r </code></pre>
<div class="figure">
<img src="/Pictures/Listening_on_port.PNG" />

</div>
<p>Now that this process is running we can make some requests:</p>
<pre class="bash"><code>curl &quot;http://127.0.0.1:8000/mean&quot;</code></pre>
<p><code>[-0.2278]</code></p>
<p>Providing a parameter using <code>?var=</code> syntax:</p>
<pre class="bash"><code>curl &quot;http://127.0.0.1:8000/mean?samples=10000&quot;</code></pre>
<p><code>[0.007]</code></p>
<p>Making a request using <code>&quot;a=&amp;b=&quot;</code> syntax:</p>
<pre class="bash"><code>curl --data &quot;a=4&amp;b=3&quot; &quot;http://127.0.0.1:8000/sum&quot;</code></pre>
<p><code>[7]</code></p>
<p>Using JSON syntax:</p>
<pre class="bash"><code>curl --data &#39;{&quot;a&quot;:4, &quot;b&quot;:5}&#39; http://127.0.0.1:8000/sum</code></pre>
<p><code>[9]</code></p>
<p>Make sure to close the job when you are done testing the api!</p>
</div>
<div id="hosting-the-api" class="section level2">
<h2>Hosting the api</h2>
<p>So now that we know how to use the plumer package let’s get our hands dirty…</p>
<div id="create-a-basic-model" class="section level3">
<h3>Create a basic model</h3>
<p>For our practical example we will build a basic caret rergession model and service it via an api so that someone can request a prediction by giving properly named inputs for the model.</p>
<p>Let’s predict how long an animal will sleep given some descriptors of said animal</p>
<p>What the data looks like:</p>
<pre class="r"><code>example_data &lt;- 
ggplot2::msleep %&gt;% 
    select(sleep_total,vore,bodywt,brainwt,awake) %&gt;% 
    na.omit()

example_data</code></pre>
<pre><code>## # A tibble: 51 x 5
##    sleep_total vore   bodywt brainwt awake
##          &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1        17   omni    0.48  0.0155    7  
##  2        14.9 omni    0.019 0.00029   9.1
##  3         4   herbi 600     0.423    20  
##  4        10.1 carni  14     0.07     13.9
##  5         3   herbi  14.8   0.0982   21  
##  6         5.3 herbi  33.5   0.115    18.7
##  7         9.4 herbi   0.728 0.0055   14.6
##  8        12.5 herbi   0.42  0.0064   11.5
##  9        10.3 omni    0.06  0.001    13.7
## 10         8.3 omni    1     0.0066   15.7
## # ... with 41 more rows</code></pre>
<p>Construct a naive model</p>
<pre class="r"><code>example_model &lt;-  
    caret::train(form = sleep_total~., data = example_data,method = &quot;rf&quot;)

# example_model %&gt;% saveRDS(&quot;data/example_model.rds&quot;)

example_model</code></pre>
<pre><code>## Random Forest 
## 
## 51 samples
##  4 predictor
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 51, 51, 51, 51, 51, 51, ... 
## Resampling results across tuning parameters:
## 
##   mtry  RMSE       Rsquared   MAE      
##   2     1.7612212  0.8756261  1.3182399
##   4     1.0041945  0.9582245  0.7173262
##   6     0.6508145  0.9789417  0.4539108
## 
## RMSE was used to select the optimal model using the smallest value.
## The final value used for the model was mtry = 6.</code></pre>
<p>Simple enough to train on this data and without any tuning we can assume a margin of error less than 1/2 an hour…</p>
</div>
<div id="create-the-api" class="section level3">
<h3>Create the api</h3>
<p>OK, so we need to first define the <code>plumber.R</code> file that we will serve.</p>
<p>Notice that we can define the template very verbosely so that we can both leverage the GET protocol to feedback some characteristics and to populate the HTML page should a user inspect the api to learn how to use it.</p>
<p>This was based on the awesome post by blogger shirin:<br />
<a href="https://shirinsplayground.netlify.com/2018/01/plumber/" class="uri">https://shirinsplayground.netlify.com/2018/01/plumber/</a></p>
<pre class="r"><code># script name:
# plumber.R

# set API title and description to show up in curl &quot;http://127.0.0.1:8000/mean&quot;/__swagger__/
#&#39; @apiTitle Run predictions for the total hours of sleep of an animal
#&#39; @apiDescription This API takes various animal&#39;s data on factors related to sleep and predicts how long the animal will sleep on its next cycle.
#&#39; indicates hours of sleep

# load model
# this path would have to be adapted if you would deploy this
# load(&quot;/Users/shiringlander/Documents/Github/shirinsplayground/data/model_rf.RData&quot;)
readRDS(&quot;/usr/etc/learning_api_in_R/data/example_model.rds&quot;)

#&#39; Log system time, request method and HTTP user agent of the incoming request
#&#39; @filter logger
function(req){
  cat(&quot;System time:&quot;, as.character(Sys.time()), &quot;\n&quot;,
      &quot;Request method:&quot;, req$REQUEST_METHOD, req$PATH_INFO, &quot;\n&quot;,
      &quot;HTTP user agent:&quot;, req$HTTP_USER_AGENT, &quot;@&quot;, req$REMOTE_ADDR, &quot;\n&quot;)
  plumber::forward()
}

# core function follows below:
# define parameters with type and description
# name endpoint
# return output as html/text
# specify 200 (okay) return

#&#39; predict Chronic Kidney Disease of test case with Random Forest model
#&#39; @param   vore Character variable. Options are : carni, herbi, insecti, omni.
#&#39; @param   bodywt:numeric Numeric variable. Weight in lb of the animal.
#&#39; @param   brainwt:numeric Numeric variable. Weight in lb of the animal.
#&#39; @param   awake:numeric Numeric variable. Time animal has been awake.
#&#39; @post /predict
#&#39; @html
#&#39; @response 200 Returns the hour(s) prediction from the Random Forest model predicting hours of next sleep
calculate_prediction &lt;- function(vore,bodywt,brainwt,awake) {
  
  # make data frame from parameters
  input_data &lt;&lt;- data.frame(vore,bodywt,brainwt,awake,
                                                        stringsAsFactors = FALSE)
  
  input_data &lt;- 
    input_data %&gt;% 
    mutate(
        vore = vore %&gt;% as.numeric(),
            bodywt = bodywt %&gt;% as.numeric(),
            brainwt = brainwt %&gt;% as.numeric(),
            awake = awake %&gt;% as.numeric()
    )
  
  # and make sure they really are the right format
  if(all(input_data[&quot;vore&quot;] %&gt;% class != &quot;character&quot;)){
    res$status &lt;- 400
    res$body &lt;- &quot;Parameters have to be in the right format. vore - character&quot;
  }
  
  if( all(input_data[c(&quot;bodywt&quot;,&quot;brainwt&quot;,&quot;awake&quot;)] %&gt;% class != &quot;numeric&quot;) ){
    res$status &lt;- 400
    res$body &lt;- &quot;Parameters have to be in the right format. vore - character&quot;
  }
  
  # validation for parameter
  if (any(is.na(input_data))) {
    res$status &lt;- 400
    res$body &lt;- &quot;Parameters have to be numeric or integers - NA&#39;s intriduced by coercion&quot;
  }

  # predict and return result
  pred_rf &lt;&lt;- predict(example_model, input_data)
  paste(&quot;----------------\nNext sleep cycle predicted to be&quot;, as.character(pred_rf), &quot;\n----------------\n&quot;)
}</code></pre>
<p>Setup executable script for the server to execute:</p>
<p>Let’s call this <code>Serve_api.R</code></p>
<pre class="r"><code>#!/usr/bin/env R
library(EightyR)
load_toolbox()
load_pkg(&quot;plumber&quot;)
r &lt;- plumb(&quot;plumber.R&quot;)
r$run(host = &quot;0.0.0.0&quot;, port=8000)</code></pre>
<p>OK, so up to now we have setup all the files we need to serve this api. Now we can ssh into a server and clone this repo over there.</p>
<p>Remember to change the file paths in the script to suite your new machine or cd into the repository before running the script.</p>
<p>For this experiment I quickly initiaited an AWS EC2 instance that we can serve the api with.</p>
<p>Note that with AWS linux you need to make sure all the dependancies are installed.</p>
</div>
<div id="ssh-into-the-server" class="section level3">
<h3>SSH into the server</h3>
<p>In any shell:</p>
<pre class="bash"><code>ssh -i &quot;path/{My_Private_Key}.pem&quot; ec2-user@ec2{My_IP}.eu-west-1.compute.amazonaws.com</code></pre>
<p>Clone the repo with your code:</p>
<pre class="bash"><code>git clone origin https://github.com/lurd4862/Testing_apis_R.git</code></pre>
<p>Change the paths referencing your model…</p>
<p>Cd into the repository…</p>
<p>Run the process in a shell:</p>
<pre class="bash"><code>Rscript Serve_api.R</code></pre>
<p>You can background this process with a noup command so that the api does not stop when you leave this shell.</p>
<p>Now that the api is running on the port we specified in the run script we can access it:</p>
<p>request the following test case using a json input</p>
<pre class="bash"><code>
curl -H &quot;Content-Type: application/json&quot; -X GET -d &#39;{&quot;vore&quot;:&quot;carni&quot;, &quot;bodywt&quot;:85, &quot;brainwt&quot;:0.325, &quot;awake&quot;:17.8}&#39; http://127.0.0.1:8000/predict
</code></pre>
<p><code>Next sleep cycle predicted to be 10.9981933333333</code></p>
<p>curl -H “Content-Type: application/json” -X GET -d ‘{“vore”:“carni”, “bodywt”:85, “brainwt”:0.325, “awake”:17.8}’ ec2-34-242-232-117.eu-west-1.compute.amazonaws.com/predict</p>
<p>ec2-34-242-232-117.eu-west-1.compute.amazonaws.com/predict?vore=“carni”?bodywt=85?brainwt=0.325?awake=17.8</p>
</div>
</div>
